### PR TITLE
Add sorting by event number for equal device names

### LINKED ISSUE #2: Cannot remap keys on Cherry keyboard
I cannot remap keys on my Cherry Wired Keyboard. ``evremap config.toml`` does not ouput an error message, but does not have any effect. ``evremap list-devices`` shows two devices named "Cherry GmbH CHERRY Wired Keyboard' with two different events. I have no clue what is the right event for the keyboard, but maybe ``evremap`` takes the wrong one. The keyboard name seems to be ambiguous.

I have another keyboard, the Logitech K380 bluetooth keyboard, which has three devices. But these devices have three different names, "Keyboard K380 Keyboard", "Keyboard K380 System Control" and "Keyboard K380 Consumer Control", and taking the first one works.

### PR DESCRIPTION
**Pull request by bronvic**
fixes #2

This additional sorting by event number if names are equal solves my problem
I can't be 100% sure that it will always work. I made some reboots and found out that event number is changing, but correct keyboard always has less number

These changes would not affect users without devices with duplicate names and would not affect previous workflow if something wrong in parsing device path

### CODE REVIEW

**Comment by wez** [comment]
Thanks for doing this; you encouraged me to put together efbdbd7 which uses a similar technique, but also adds a way to solve ambiguous names!

**Comment by bronvic** [comment]
Thank you for such quick response and your time :)

I see one minor problem with your solution. So, I have two entries for my keyboard for whatever reason
```
Name: LingYao ShangHai Thumb Keyboard
Path: /dev/input/event12
Phys: usb-0000:00:14.0-5/input0

Name: LingYao ShangHai Thumb Keyboard
Path: /dev/input/event14
Phys: usb-0000:00:14.0-5/input1
```

I put `usb-0000:00:14.0-5/input1` into config, because this device is what I need. But if I connect keyboard to another usb port, its physical address obviously will be changed
```
Name: LingYao ShangHai Thumb Keyboard
Path: /dev/input/event12
Phys: usb-0000:00:14.0-1/input0

Name: LingYao ShangHai Thumb Keyboard
Path: /dev/input/event14
Phys: usb-0000:00:14.0-1/input1
```

However postfix `/input1` stays the same. What do you think? Maybe it can be configured to use input number? Or both physical path or input number?

**Comment by wez** [comment]
I'm not sure if we can be smarter about this; the `Path` seems to vary across a reboot (presumably there is some non-determinism due to latency of USB bus polling on startup). I don't think there are any other stable identifiers that we could use "safely" across a device re-plug, so I think the best canonical identifier we have is the `Phys`.

Hmm, another option then might be:

* Instead of sorting the device list by `Name, Path`, sort it by `Name, Phys`, so that we guarantee that the lower `/input0` sorts first
* Add our own concept of `Index` in the config, so that you could use this to select the `/input1` keyboard if desired, without encoding the physical address in the config:

```toml
device_name = "LingYao ShangHai Thumb Keyboard"
index = 1
```

**Comment by bronvic** [comment]
Maybe adding "input" will be good idea. But i worry that it can be hard to explain to user what them need to put in this variable

Maybe it can be done if someone request this feature)

**Pull request closed without merging**
